# Generated by Django 5.1 on 2024-08-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
